### PR TITLE
add header

### PR DESCRIPTION
**Pull request by fiennyangeln**
Bug 1442636
Add header
@djmitche please review :)

### CODE REVIEW

**Comment by djmitche** [comment]
@fiennyangeln this looks good, but can you modify the [commit message](https://docs.taskcluster.net/manual/design/devel/best-practices/commits)?  Then I'll merge it and make a release, and you can start working on upgrading services :)

**Comment by fiennyangeln** [comment]
@djmitche Ok modified based on the commit message guidelines. Moreover, does it have to be like that for other commit ? :) And, which services do you mean? :D

**Comment by djmitche** [comment]
That updated commit message is great.  Yes, ideally all commits have a good title and description.

The services are in the first three categories in https://docs.taskcluster.net/reference (Taskcluster Platform, Core Services, and Integrations).  Plus ec2-manager, which doesn't show up there for reasons we won't get into.

**Comment by fiennyangeln** [comment]
@djmitche do you mean adding the value to the option to be passed when creating API on that service? :D Because it seems like it is already defaulted to use the allowedCORSOrigin and on the Hooks, auth, queue repo, they dont send the value, so the default one (the allowed cors origin) is used. Is my understanding correct ? :D https://github.com/taskcluster/taskcluster-lib-api/blob/master/src/api.js#L811

**Pull request merged**
