### PR TITLE
Bug-1347158 : Added http response json schema for ping endpoint

### PR DESCRIPTION
**Pull request by Saurabh-Pakhare**
Bug-1347158 (https://bugzilla.mozilla.org/show_bug.cgi?id=1347158#c1)
Added json schema for the pint endpoint.

### CODE REVIEW

**Comment by ccooper** [comment]
@Saurabh-Pakhare Are you planning to continue with this?

**Comment by Saurabh-Pakhare** [comment]
@ccooper Yes I will be working on it now, apologies for the delay

**Comment by Saurabh-Pakhare** [comment]
@djmitche So it will not load schemas for any other api as well?

**Comment by djmitche** [comment]
Right, as-implemented right now it does not.

Here's what I would suggest: in taskcluster-lib-validate, add a method to SchemaSet that will load additional schemas from a given directory and return a *new* SchemaSet object containing both the original and newly-loaded schemas.  Then we can use that method in taskcluster-lib-api.

**Comment by Saurabh-Pakhare** [comment]
I think that adding such method in taskcluster-lib-validate SchemaSet would need some refactoring, can't we simply move the schemas directory at the project root level, wouldn't that solve the problem?

**Comment by djmitche** [comment]
I'm not sure what you're suggesting -- perhaps give it a try and see how it works?

**Comment by Saurabh-Pakhare** [comment]
@djmitche In a previous comment you mentioned this 
> the SchemaSet that is passed to the APIBuilder does not load schemas from this directory
(src/schemas in this library), so just adding output: 'ping.json#' will not do the trick.

And the taskcluster-lib-validate's README also says this 
> Schemas are typically stored under schemas/ in the repository root, with a directory per schema version.

So i was thinking in taskcluster-lib-api can we move the schema from `src/schemas` to taskcluster-lib-api/schemas/{version}, i.e taking it out from src and move it in schemas folder at root level so then taskcluster-lib-validate will be able to load it as it does in other projects

**Comment by djmitche** [comment]
Let's see if it works?

**Comment by djmitche** [comment]
Let's see if it works?

**Comment by Saurabh-Pakhare** [comment]
Yeah so for testing it I will have to integrate with taskcluster-lib-validate locally right?

**Pull request closed without merging**
