### PR TITLE
move local signature validator to auth

### PR DESCRIPTION
**Pull request by djmitche**
This also removed a bunch of dead code for the old (`auth:credentials`) way of authenticating.

See https://github.com/taskcluster/taskcluster-auth/pull/39

### CODE REVIEW

**Comment by djmitche** [comment]
I think this should ship with a major version bump for the library, so that existing services can keep using the old library.

**Comment by jonasfj** [comment]
So you'll move `test/auth_test.js` into the `tc-auth`, right?

**Comment by djmitche** [comment]
Hm, `test/auth_test.js` is actually testing the mock auth server, which I discovered when introducing errors into the real signature validator did not cause any test failures.  But, yes, (a) that will be a good starting point for auth tests and (b) I should remove it from tc-lib-api and start using fakeauth there.

**Comment by jonasfj** [comment]
`r+`, but just so you know...

Porting all tests to use fakeAuth is a non-trivial effort. There is a lot of components to move.

**Comment by djmitche** [comment]
Yeah, we can take our time porting to fakeauth.  Per component, it's not that much work.

**Comment by djmitche** [comment]
OK, I stripped down the tests a bit (so they focus on stuff the API is doing, around scope validation) and refactored to use fakeauth.

**Comment by jonasfj** [comment]
Looks okay.. `r+` stands.

**Pull request merged**
