### PR TITLE
update taskcluster-lib-validate to 3.1.0

### PR DESCRIPTION
**Pull request by ydidwania**

### CODE REVIEW

**Comment by djmitche** [comment]
Oh, good thinking.  We'll need a new version of lib-api at the same time.

**Comment by djmitche** [comment]
Oh, Travis, Y U so slow..

**Comment by djmitche** [comment]
v8.2.0, should be published in a few minutes

**Comment by djmitche** [comment]
it's out now

**Comment by ydidwania** [comment]
Should I update this along with `taskcliuster-lib-validate` ?

**Comment by djmitche** [comment]
Yes please.  Let's start with just one service and see how it goes.  Queue might be a good choice.

**Pull request merged**
